### ISSUE TITLE
datas.yml

### ISSUE THREAD

**Issue by LucidAPs** [SkytAsul/CitizensText#1]
Please allow users to make changes to datas.yml and actually have them be saved. It will save so much time when you simply want to edit or change something.

**Comment by SkytAsul** [comment]
Unfortunately, I can't make the data file sync while the server is running.

**Comment by LucidAPs** [comment]
Okey how about when it's offline? It doesn't save any edits no matter the situation unless it's done in game. I hope you can figure out.... it's killing me, it would be so much faster to do changes and editing from the .yml

**Comment by SkytAsul** [comment]
It's already possible 🤔 you just have to stop your server, edit the file, save it, and launch the server again.
