### ISSUE TITLE
CitizensText is loading NPCs on Paper

### ISSUE THREAD

**Issue by PapiCapi** [SkytAsul/CitizensText#3]
To reproduce, you just have to create an NPC on Paper ( 1.16.4 ), go somewhere else and type /lag ( you'll see the chunks generated ) . Now install CitizensText and add a text to the NPC and now the chunks will be kept loaded next to this NPC

**Comment by SkytAsul** [comment]
The chunks are not loaded when CitizensText is not installed?

**Comment by PapiCapi** [comment]
Nevermind, sorry for the useless issue : it was the fault of the spawn chunks and Citizens
